// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDknnLXZ5Ay7yO6a4YFAm5r_enOAF8yL5U',
    appId: '1:224823018664:web:3b76b2df192ba2ab726e9d',
    messagingSenderId: '224823018664',
    projectId: 'flutter-firebase-c18db',
    authDomain: 'flutter-firebase-c18db.firebaseapp.com',
    storageBucket: 'flutter-firebase-c18db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj_q2IGwnsbPWCv_bm-rMmwdUtDk-fe9g',
    appId: '1:945457374825:android:70ff5ab486cccf590164f8',
    messagingSenderId: '945457374825',
    projectId: 'fire-flutter-ce3f9',
    storageBucket: 'fire-flutter-ce3f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOe69ZEQ9KsyZpTe6e0ua1-EpDh_ODGCs',
    appId: '1:945457374825:ios:10ca3b66ca9a4ed60164f8',
    messagingSenderId: '945457374825',
    projectId: 'fire-flutter-ce3f9',
    storageBucket: 'fire-flutter-ce3f9.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZnVOsSSgFPLZP1TtEvIF-ju4mMcVP4P0',
    appId: '1:224823018664:ios:15cb03bf5b046c09726e9d',
    messagingSenderId: '224823018664',
    projectId: 'flutter-firebase-c18db',
    storageBucket: 'flutter-firebase-c18db.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9IREGksqECf1lQg3D2qMuNzsE3gGL1f4',
    appId: '1:945457374825:web:b7c255b6deeeae460164f8',
    messagingSenderId: '945457374825',
    projectId: 'fire-flutter-ce3f9',
    authDomain: 'fire-flutter-ce3f9.firebaseapp.com',
    storageBucket: 'fire-flutter-ce3f9.firebasestorage.app',
    measurementId: 'G-23TQS8DFQN',
  );

}